[package]
name = "hyperion"
edition.workspace = true
version.workspace = true
publish = false
readme = "README.md"

[features]
reflect = [
    "dep:bevy_reflect",
    "bevy_app/reflect_auto_register",
    "bevy_ecs/reflect_auto_register",
    "bevy_reflect/auto_register_inventory",
    "bevy_reflect/uuid",
    "hyperion-clap/reflect",
    "hyperion-command/reflect",
    "hyperion-crafting/reflect",
    "hyperion-data/reflect",
    "hyperion-entity/reflect",
    "hyperion-gui/reflect",
    "hyperion-inventory/reflect",
    "hyperion-item/reflect",
    "hyperion-net/reflect",
    "hyperion-permission/reflect",
    "hyperion-proxy-proto/reflect",
    "hyperion-simulation/reflect",
    "hyperion-utils/reflect",
    "hyperion-world/reflect",
]
ecs_debug = ["bevy_ecs/trace", "bevy_ecs/debug"]

[[bench]]
harness = false
name = "set"

[dependencies]
hyperion-clap.workspace = true
hyperion-command.workspace = true
hyperion-crafting.workspace = true
hyperion-data.workspace = true
hyperion-entity.workspace = true
hyperion-gui.workspace = true
hyperion-inventory.workspace = true
hyperion-item.workspace = true
hyperion-net.workspace = true
hyperion-permission.workspace = true
hyperion-proxy-proto.workspace = true
hyperion-simulation.workspace = true
hyperion-utils.workspace = true
hyperion-world.workspace = true

valence_bytes.workspace = true
valence_ident.workspace = true
valence_protocol.workspace = true

bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_reflect = { workspace = true, optional = true }
bevy_tasks.workspace = true
bevy_time.workspace = true

fastrand.workspace = true
geometry.workspace = true
glam.workspace = true
libc.workspace = true
libdeflater.workspace = true
rayon.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
hyperion-world.workspace = true

approx.workspace = true
divan.workspace = true
fastrand.workspace = true
serial_test.workspace = true

[lints]
workspace = true
