[package]
name = "hyperion-entity"
edition.workspace = true
version.workspace = true
publish = false
readme = "README.md"

[features]
reflect = [
    "dep:bevy_reflect",
    "bevy_app/reflect_auto_register",
    "bevy_ecs/reflect_auto_register",
    "bevy_reflect/auto_register_inventory",
    "hyperion-utils/reflect",
]

[dependencies]
hyperion-utils.workspace = true

valence_generated.workspace = true
valence_protocol.workspace = true
valence_text.workspace = true

bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_reflect = { workspace = true, optional = true }

bytemuck.workspace = true
enumset.workspace = true
fastrand.workspace = true
geometry.workspace = true
glam.workspace = true
serde.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
