[package]
name = "bvh-data"
edition.workspace = true
version.workspace = true
publish = false
readme = "README.md"

[dependencies]
arrayvec.workspace = true
bytes.workspace = true
fast_hilbert = "2"
fastrand.workspace = true
glam.workspace = true
heapless.workspace = true
more-asserts.workspace = true
tracing.workspace = true

[lints]
workspace = true
